# Generated by Django 2.2.3 on 2019-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_5566',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30, verbose_name='ID号')),
                ('game_title', models.CharField(max_length=150, verbose_name='游戏名称')),
            ],
        ),
    ]
